"""LLM completion with retries, circuit breaker, and model fallback."""

from __future__ import annotations

import asyncio
import logging
import time
from dataclasses import dataclass

import httpx

from app.core.config import Industry, Settings

logger = logging.getLogger(__name__)


@dataclass(slots=True)
class LlmResult:
    sql: str | None
    narrative: str
    model: str
    prompt_tokens: int = 0
    completion_tokens: int = 0
    error: str | None = None
    timed_out: bool = False
    circuit_open: bool = False


class _CircuitBreaker:
    """Fail fast when the LLM provider is clearly degraded."""

    def __init__(self, *, failure_threshold: int = 3, cooldown_seconds: float = 45) -> None:
        self.failure_threshold = failure_threshold
        self.cooldown_seconds = cooldown_seconds
        self._failures = 0
        self._opened_at: float | None = None

    def allow(self) -> bool:
        if self._opened_at is None:
            return True
        if time.monotonic() - self._opened_at >= self.cooldown_seconds:
            self._opened_at = None
            self._failures = 0
            return True
        return False

    def record_success(self) -> None:
        self._failures = 0
        self._opened_at = None

    def record_failure(self) -> None:
        self._failures += 1
        if self._failures >= self.failure_threshold:
            self._opened_at = time.monotonic()


_CIRCUIT = _CircuitBreaker()


def _slim_system_prompt(industry: Industry, schema_hints: str | None) -> str:
    hints = (schema_hints or "").strip()
    hint_block = f"\nDomain context (use only this):\n{hints}\n" if hints else "\n"
    return (
        f"You are NQL Insight for {industry.value} analytics. "
        "Return one PostgreSQL SELECT only — schema-qualified, read-only, "
        "LIMIT <= 50. No markdown, no commentary. "
        "Obey Resolved entity, Mandatory filters, ALWAYS/NEVER rules exactly. "
        "Never invent tables or columns. Never confuse salesperson (dim_salesman) "
        "with dealer (dim_dealer)."
        f"{hint_block}"
    )


def _extract_sql(content: str) -> str | None:
    sql = (content or "").strip()
    if not sql:
        return None
    if sql.startswith("```"):
        sql = sql.strip("`")
        if sql.lower().startswith("sql"):
            sql = sql[3:].strip()
    return sql or None


async def _one_completion(
    *,
    settings: Settings,
    model: str,
    system: str,
    question: str,
    timeout: float,
) -> LlmResult:
    api_key = settings.llm_api_key.get_secret_value()
    payload = {
        "model": model,
        "temperature": settings.llm_temperature,
        "max_tokens": min(settings.llm_max_completion_tokens, 400),
        "messages": [
            {"role": "system", "content": system},
            {"role": "user", "content": question},
        ],
    }
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }
    url = settings.llm_base_url.rstrip("/") + "/chat/completions"
    try:
        async with httpx.AsyncClient(timeout=timeout) as client:
            response = await client.post(url, headers=headers, json=payload)
            response.raise_for_status()
            body = response.json()
    except httpx.TimeoutException:
        return LlmResult(
            sql=None,
            narrative="",
            model=model,
            error="Timeout",
            timed_out=True,
        )
    except Exception as exc:
        return LlmResult(
            sql=None,
            narrative="",
            model=model,
            error=f"{type(exc).__name__}: {exc}"[:240],
        )

    choice = (body.get("choices") or [{}])[0]
    content = ((choice.get("message") or {}).get("content") or "").strip()
    usage = body.get("usage") or {}
    sql = _extract_sql(content)
    return LlmResult(
        sql=sql,
        narrative="SQL was generated by the language model and validated by guardrails.",
        model=body.get("model") or model,
        prompt_tokens=int(usage.get("prompt_tokens") or 0),
        completion_tokens=int(usage.get("completion_tokens") or 0),
        error=None if sql else "Invalid model response (empty SQL)",
    )


async def complete_chat(
    *,
    settings: Settings,
    industry: Industry,
    question: str,
    schema_hints: str | None = None,
) -> LlmResult:
    api_key = settings.llm_api_key.get_secret_value()
    if not api_key:
        return LlmResult(
            sql=None,
            narrative="",
            model=settings.llm_default_model,
            error="No LLM API key configured",
        )

    if not _CIRCUIT.allow():
        return LlmResult(
            sql=None,
            narrative="The language model provider is temporarily unavailable.",
            model=settings.llm_default_model,
            error="AI service is currently degraded",
            circuit_open=True,
        )

    timeout = float(settings.nlq_llm_timeout_seconds)
    system = _slim_system_prompt(industry, schema_hints)
    primary = settings.llm_default_model
    fallback = (settings.llm_fallback_model or "").strip() or None

    attempts: list[str] = [primary]
    if fallback and fallback != primary:
        attempts.append(fallback)

    last: LlmResult | None = None
    for model_index, model in enumerate(attempts):
        retries = 1 + (0 if model_index else settings.nlq_llm_max_retries)
        for attempt in range(retries):
            result = await _one_completion(
                settings=settings,
                model=model,
                system=system,
                question=question,
                timeout=timeout,
            )
            last = result
            if result.sql:
                _CIRCUIT.record_success()
                return result
            transient = result.timed_out or (
                result.error
                and any(token in result.error.lower() for token in ("5", "timeout", "unavailable", "connect"))
            )
            if not transient:
                break
            if attempt + 1 < retries:
                await asyncio.sleep(0.4 * (2**attempt))
        # Fall through to next model on repeated primary failure.
        logger.info("LLM model %s failed; trying next if available", model)

    _CIRCUIT.record_failure()
    assert last is not None
    if last.circuit_open:
        return last
    return LlmResult(
        sql=None,
        narrative=last.narrative
        or f"The language model call failed: {last.error or 'unknown'}.",
        model=last.model,
        prompt_tokens=last.prompt_tokens,
        completion_tokens=last.completion_tokens,
        error=last.error or "Unavailable",
        timed_out=last.timed_out,
    )


def circuit_stats() -> dict[str, object]:
    return {
        "open": not _CIRCUIT.allow(),
        "failures": _CIRCUIT._failures,
        "openedAt": _CIRCUIT._opened_at,
    }
