"""LLM completion helper. Works without a key by returning empty SQL."""

from __future__ import annotations

from dataclasses import dataclass

import httpx

from app.core.config import Industry, Settings
from app.semantic.service import SemanticService


@dataclass(slots=True)
class LlmResult:
    sql: str | None
    narrative: str
    model: str
    prompt_tokens: int = 0
    completion_tokens: int = 0


async def complete_chat(
    *,
    settings: Settings,
    industry: Industry,
    question: str,
) -> LlmResult:
    api_key = settings.llm_api_key.get_secret_value()
    if not api_key:
        return LlmResult(
            sql=None,
            narrative="",
            model=settings.llm_default_model,
        )

    # Minimal OpenAI-compatible chat completion. SQL must still pass guardrails.
    system = (
        f"You are NQL Insight for the {industry.value} industry. "
        "Return a single PostgreSQL SELECT statement only, schema-qualified, "
        "read-only, with LIMIT <= 200. No markdown."
    )
    payload = {
        "model": settings.llm_default_model,
        "temperature": settings.llm_temperature,
        "max_tokens": settings.llm_max_completion_tokens,
        "messages": [
            {"role": "system", "content": system},
            {"role": "user", "content": question},
        ],
    }
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }
    url = settings.llm_base_url.rstrip("/") + "/chat/completions"
    try:
        async with httpx.AsyncClient(timeout=settings.llm_timeout_seconds) as client:
            response = await client.post(url, headers=headers, json=payload)
            response.raise_for_status()
            body = response.json()
    except Exception as exc:
        return LlmResult(
            sql=None,
            narrative=f"The language model call failed: {type(exc).__name__}.",
            model=settings.llm_default_model,
        )

    choice = (body.get("choices") or [{}])[0]
    content = ((choice.get("message") or {}).get("content") or "").strip()
    usage = body.get("usage") or {}
    sql = content
    if sql.startswith("```"):
        sql = sql.strip("`")
        if sql.lower().startswith("sql"):
            sql = sql[3:].strip()
    return LlmResult(
        sql=sql or None,
        narrative="SQL was generated by the language model and validated by guardrails.",
        model=body.get("model") or settings.llm_default_model,
        prompt_tokens=int(usage.get("prompt_tokens") or 0),
        completion_tokens=int(usage.get("completion_tokens") or 0),
    )


# SemanticService kept importable for future prompt packing.
_ = SemanticService
