"""
core/evidence_builder.py
Lightweight execution evidence (ISANA PHASE 7.5 inspired).
"""
from __future__ import annotations

import hashlib
import uuid
from datetime import datetime, timezone
from typing import Any

import pandas as pd
import streamlit as st

try:
    from config.constants import (
        MAX_EVIDENCE_HISTORY,
        BADGE_DETERMINISTIC,
        BADGE_FALLBACK,
        BADGE_CACHED,
    )
except ImportError:
    MAX_EVIDENCE_HISTORY = 20
    BADGE_DETERMINISTIC = {
        "icon": "✅", "label": "Deterministic", "colour": "green",
    }
    BADGE_FALLBACK = {
        "icon": "⚠️", "label": "AI Generated", "colour": "orange",
    }
    BADGE_CACHED = {
        "icon": "🔒", "label": "Cached", "colour": "blue",
    }

BADGE_SEMANTIC = {
    "icon": "🧠", "label": "Semantic + AI", "colour": "indigo",
}


def _sha(text: str, n: int) -> str:
    return hashlib.sha256((text or "").encode("utf-8")).hexdigest()[:n]


def build_evidence(
    sql: str,
    result_df: pd.DataFrame | None,
    execution_path: str,
    question: str,
) -> dict[str, Any]:
    """Build advisory evidence record for a query execution."""
    path = (
        execution_path
        if execution_path in ("deterministic", "fallback", "cache", "semantic")
        else "fallback"
    )
    ok = result_df is not None
    evidence: dict[str, Any] = {
        "evidence_id": str(uuid.uuid4()),
        "query_hash": _sha(sql or "", 16),
        "execution_path": path,
        "result_row_count": int(len(result_df)) if ok else 0,
        "result_col_count": int(result_df.shape[1]) if ok else 0,
        "execution_status": "success" if ok else "error",
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "question_fingerprint": _sha(question or "", 12),
        "advisory_only": True,
    }
    _store_evidence(evidence)
    _bump_stats(path)
    return evidence


def get_execution_badge(evidence: dict | None) -> dict[str, Any]:
    """Map evidence execution_path to a UI badge."""
    if not evidence:
        return {
            **BADGE_FALLBACK,
            "tooltip": "No execution evidence available.",
        }
    path = evidence.get("execution_path", "fallback")
    if path == "deterministic":
        return {
            **BADGE_DETERMINISTIC,
            "tooltip": "Resolved via metric registry and rule-based SQL compiler.",
        }
    if path == "cache":
        return {
            **BADGE_CACHED,
            "tooltip": "Served from session or disk cache — no new LLM call.",
        }
    if path == "semantic":
        return {
            **BADGE_SEMANTIC,
            "tooltip": "SQL generated by AI with business glossary + semantic layer grounding.",
        }
    return {
        **BADGE_FALLBACK,
        "tooltip": "Generated by AI fallback path (LLM SQL).",
    }


def _store_evidence(evidence: dict[str, Any]) -> None:
    try:
        if "execution_evidence" not in st.session_state:
            st.session_state.execution_evidence = []
        hist = st.session_state.execution_evidence
        hist.append(evidence)
        st.session_state.execution_evidence = hist[-MAX_EVIDENCE_HISTORY:]
    except Exception:
        pass


def _bump_stats(path: str) -> None:
    try:
        if "query_stats" not in st.session_state:
            st.session_state.query_stats = {
                "deterministic": 0, "fallback": 0, "cache": 0,
            }
        stats = st.session_state.query_stats
        if path in stats:
            stats[path] = int(stats.get(path, 0)) + 1
    except Exception:
        pass
