"""Insurance analytics schema ported from legacy ``001_insurance_schema.sql``.

Revision ID: 0001_insurance_schema
Revises:
Create Date: 2026-09-10

Grants SELECT to ``askdb_reader`` (askdb uses a dedicated analytics reader role).
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0001_insurance_schema"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS insurance")
    op.execute(
        """
        CREATE TABLE insurance.dim_product (
            product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            product_code TEXT NOT NULL UNIQUE,
            product_name TEXT NOT NULL,
            line_of_business TEXT NOT NULL,
            product_family TEXT,
            coverage_type TEXT,
            active_flag BOOLEAN NOT NULL DEFAULT TRUE
        )
        """
    )
    op.execute(
        """
        CREATE TABLE insurance.dim_agent (
            agent_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            agent_code TEXT NOT NULL UNIQUE,
            agent_name TEXT NOT NULL,
            channel_name TEXT,
            branch_name TEXT,
            active_flag BOOLEAN NOT NULL DEFAULT TRUE
        )
        """
    )
    op.execute(
        """
        CREATE TABLE insurance.dim_region (
            region_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            region_code TEXT NOT NULL UNIQUE,
            region_name TEXT NOT NULL,
            state_name TEXT,
            country_name TEXT NOT NULL DEFAULT 'India'
        )
        """
    )
    op.execute(
        """
        CREATE TABLE insurance.dim_policy (
            policy_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            policy_number TEXT NOT NULL UNIQUE,
            product_id BIGINT NOT NULL
                REFERENCES insurance.dim_product (product_id),
            agent_id BIGINT REFERENCES insurance.dim_agent (agent_id),
            region_id BIGINT REFERENCES insurance.dim_region (region_id),
            customer_key TEXT,
            inception_date DATE NOT NULL,
            expiry_date DATE NOT NULL,
            policy_status TEXT NOT NULL,
            coverage_tier TEXT,
            sum_insured NUMERIC(18,2),
            cancelled_flag BOOLEAN NOT NULL DEFAULT FALSE,
            CONSTRAINT dim_policy_dates_chk CHECK (expiry_date >= inception_date)
        )
        """
    )
    op.execute(
        """
        CREATE TABLE insurance.fact_claims (
            claim_id BIGINT PRIMARY KEY,
            claim_number TEXT NOT NULL UNIQUE,
            policy_id BIGINT NOT NULL
                REFERENCES insurance.dim_policy (policy_id),
            product_id BIGINT NOT NULL
                REFERENCES insurance.dim_product (product_id),
            region_id BIGINT REFERENCES insurance.dim_region (region_id),
            loss_date DATE,
            reported_date DATE NOT NULL,
            approved_date DATE,
            settlement_date DATE,
            claim_status TEXT NOT NULL,
            claim_type TEXT,
            reported_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
            approved_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
            paid_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
            reserve_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
            incurred_amount NUMERIC(18,2)
                GENERATED ALWAYS AS (paid_amount + reserve_amount) STORED,
            approved_flag BOOLEAN NOT NULL DEFAULT FALSE,
            repudiated_flag BOOLEAN NOT NULL DEFAULT FALSE,
            fraud_suspected_flag BOOLEAN NOT NULL DEFAULT FALSE,
            catastrophe_code TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT fact_claims_reported_chk CHECK (reported_amount >= 0),
            CONSTRAINT fact_claims_approved_chk CHECK (approved_amount >= 0),
            CONSTRAINT fact_claims_paid_chk CHECK (paid_amount >= 0),
            CONSTRAINT fact_claims_reserve_chk CHECK (reserve_amount >= 0)
        )
        """
    )
    op.execute(
        """
        CREATE TABLE insurance.fact_policy_monthly (
            policy_month_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            policy_id BIGINT NOT NULL
                REFERENCES insurance.dim_policy (policy_id),
            product_id BIGINT NOT NULL
                REFERENCES insurance.dim_product (product_id),
            agent_id BIGINT REFERENCES insurance.dim_agent (agent_id),
            region_id BIGINT REFERENCES insurance.dim_region (region_id),
            accounting_month DATE NOT NULL,
            written_premium NUMERIC(18,2) NOT NULL DEFAULT 0,
            earned_premium NUMERIC(18,2) NOT NULL DEFAULT 0,
            exposure_units NUMERIC(18,6) NOT NULL DEFAULT 0,
            active_policy_flag BOOLEAN NOT NULL DEFAULT TRUE,
            due_for_renewal_flag BOOLEAN NOT NULL DEFAULT FALSE,
            renewed_flag BOOLEAN,
            CONSTRAINT fact_policy_monthly_uq UNIQUE (policy_id, accounting_month),
            CONSTRAINT fact_policy_monthly_month_chk
                CHECK (accounting_month = date_trunc('month', accounting_month)::date),
            CONSTRAINT fact_policy_monthly_wp_chk CHECK (written_premium >= 0),
            CONSTRAINT fact_policy_monthly_ep_chk CHECK (earned_premium >= 0),
            CONSTRAINT fact_policy_monthly_eu_chk CHECK (exposure_units >= 0)
        )
        """
    )
    op.execute(
        """
        CREATE TABLE insurance.fact_operating_expense_monthly (
            expense_month_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            accounting_month DATE NOT NULL,
            product_id BIGINT REFERENCES insurance.dim_product (product_id),
            region_id BIGINT REFERENCES insurance.dim_region (region_id),
            acquisition_expense NUMERIC(18,2) NOT NULL DEFAULT 0,
            operating_expense NUMERIC(18,2) NOT NULL DEFAULT 0,
            CONSTRAINT fact_opex_monthly_uq UNIQUE (accounting_month, product_id, region_id)
        )
        """
    )

    op.execute("CREATE INDEX idx_claims_policy ON insurance.fact_claims (policy_id)")
    op.execute("CREATE INDEX idx_claims_reported_date ON insurance.fact_claims (reported_date)")
    op.execute(
        "CREATE INDEX idx_claims_reported_claim "
        "ON insurance.fact_claims (reported_date DESC, claim_id DESC)"
    )
    op.execute(
        "CREATE INDEX idx_claims_product_date ON insurance.fact_claims (product_id, reported_date)"
    )
    op.execute(
        "CREATE INDEX idx_claims_region_date ON insurance.fact_claims (region_id, reported_date)"
    )
    op.execute("CREATE INDEX idx_claims_status ON insurance.fact_claims (claim_status)")
    op.execute(
        "CREATE INDEX idx_policy_month_month ON insurance.fact_policy_monthly (accounting_month)"
    )
    op.execute(
        "CREATE INDEX idx_policy_month_product "
        "ON insurance.fact_policy_monthly (product_id, accounting_month)"
    )
    op.execute(
        "CREATE INDEX idx_policy_month_region "
        "ON insurance.fact_policy_monthly (region_id, accounting_month)"
    )

    op.execute(
        """
        CREATE OR REPLACE VIEW insurance.v_claims_enriched AS
        SELECT
            c.claim_id,
            c.claim_number,
            c.policy_id,
            p.policy_number,
            c.reported_date,
            c.loss_date,
            c.settlement_date,
            c.claim_status,
            c.claim_type,
            c.reported_amount,
            c.approved_amount,
            c.paid_amount,
            c.reserve_amount,
            c.incurred_amount,
            c.approved_flag,
            c.repudiated_flag,
            c.fraud_suspected_flag,
            pr.product_id,
            pr.product_code,
            pr.product_name,
            pr.line_of_business,
            r.region_id,
            r.region_name,
            r.state_name,
            a.agent_id,
            a.agent_name,
            a.channel_name
        FROM insurance.fact_claims c
        JOIN insurance.dim_policy p ON p.policy_id = c.policy_id
        JOIN insurance.dim_product pr ON pr.product_id = c.product_id
        LEFT JOIN insurance.dim_region r ON r.region_id = c.region_id
        LEFT JOIN insurance.dim_agent a ON a.agent_id = p.agent_id
        """
    )

    op.execute("GRANT USAGE ON SCHEMA insurance TO askdb_reader")
    op.execute("GRANT SELECT ON ALL TABLES IN SCHEMA insurance TO askdb_reader")
    op.execute(
        "ALTER DEFAULT PRIVILEGES IN SCHEMA insurance GRANT SELECT ON TABLES TO askdb_reader"
    )


def downgrade() -> None:
    op.execute("DROP SCHEMA IF EXISTS insurance CASCADE")
